spring:
    jpa:
        properties:
            hibernate.show_sql: true
            hibernate.use_sql_comments: true
            hibernate.format_sql: true
        open-in-view: false


---
spring:
    profiles: local
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        hikari:
            driver-class-name: org.h2.Driver
            jdbc-url: jdbc:h2:mem:miracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password: sa

---
spring:
    profiles: prod
