 ### 회원가입 API
POST {{host}}/api/v1/member
Content-Type: application/json

{
    "name": "강승호",
    "email": "will.seungho@gmail.com",
    "profileIcon": "RED",
    "goals": [
        "READING",
        "EXERCISE",
        "PROMISE"
    ],
    "wakeUpTime": "06:00"
}
> {%
client.global.set("AUTHORIZATION", response.body["data"])
 %}


### 내정보를 불러오는 API
GET {{host}}/api/v1/member
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

### 회원 수정 API
PUT {{host}}/api/v1/member
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "name": "호승강",
    "profileIcon": "BLUE",
    "wakeUpTime": "11:00"
}

### 회원의 알림모드를 변경하는 API
PUT {{host}}/api/v1/member/mode
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "alarmMode": "RELAX"
}

### 회원의 목표 변경 API
PUT {{host}}/api/v1/member/goal
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "goals": [
        "MEDITATION"
    ]
}

###
