POST {{host}}/api/v1/record
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "scheduleId": 1,
    "question": "질문?",
    "answer": "대답.",
    "startDateTime":  "2020-08-23T16:30:00",
    "endDateTime": "2020-08-23T17:00:00",
    "category": "EXERCISE"
}


###
