###
POST {{host}}/api/v1/schedule
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "startTime": "2020-08-06T16:30:00",
    "endTime": "2020-08-06T17:00:00",
    "category": "운동",
    "description": "운동하기",
    "loopType": "NONE"
}
###

GET {{host}}/api/v1/schedule?year=2020&month=8&day=9
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

###
