###
POST {{host}}/api/v1/schedule
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "category": "EXERCISE",
    "description": "운동하기",
    "dayOfTheWeeks": ["MON", "WED"],
    "startTime": "16:30",
    "endTime": "17:00"
}
> {%
client.global.set("SCHEDULE_ID", response.body["data"]["scheduleIds"][0]);
 %}

###

GET {{host}}/api/v1/schedule?dayOfTheWeek=MON
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

###

PUT {{host}}/api/v1/schedule/{{SCHEDULE_ID}}
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "category": "READING",
    "description": "책읽기",
    "dayOfTheWeek": "MON",
    "startTime": "08:30",
    "endTime": "10:00"
}
> {%
client.global.set("SCHEDULE_ID", response.body["data"]["scheduleId"]);
 %}

###

DELETE {{host}}/api/v1/schedule/{{SCHEDULE_ID}}
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

###

GET {{host}}/api/v1/schedule/{{SCHEDULE_ID}}/category/comment
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

###
