###
POST {{host}}/api/v1/schedule
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
    "startTime": "2020-08-06T16:30:00",
    "endTime": "2020-08-06T17:00:00",
    "category": "EXERCISE",
    "description": "운동하기",
    "loopType": "NONE"
}
> {%
client.global.set("SCHEDULE_ID", response.body["data"]["scheduleId"]);
 %}

###

GET {{host}}/api/v1/schedule?year=2020&month=8&day=6
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

###

PUT {{host}}/api/v1/schedule/{{SCHEDULE_ID}}
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

{
  "startTime": "2020-08-09T16:30:00",
  "endTime": "2020-08-09T17:00:00",
  "category": "MEDITATION",
  "description": "명상하기",
  "loopType": "DAY"
}
> {%
client.global.set("SCHEDULE_ID", response.body["data"]["scheduleId"]);
 %}

###

DELETE {{host}}/api/v1/schedule/{{SCHEDULE_ID}}
Authorization: Bearer {{AUTHORIZATION}}
Content-Type: application/json

###
