server:
    port: 8080

spring:
    profiles:
        active: local
        include:
            - domain
            - oauth
            - logging

---

spring:
    profiles: local
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        hikari:
            driver-class-name: org.h2.Driver
            jdbc-url: jdbc:h2:mem:mimo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password: sa
    jpa:
        hibernate:
            ddl-auto: update

---

spring:
    profiles: prod
