# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: deploy springboot

on:
  repository_dispatch:
    types: [deploy]
env:
  PROJECT_NAME: miracle
  PROFILE: prod
  BUCKET: depromeet-8th-warming-up-1-s3
  REGION: ap-northeast-2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Install JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Create deploy dir
      run: mkdir -p code-deploy
    - name: Move deploy code deploy script
      run: cp scripts/*.sh code-deploy/
    - name: Move code deploy config
      run: cp appspec.yml code-deploy/
    - name: Move build jar
      run: cp miracle-api/build/libs/*.jar code-deploy/
    - name: Zip build jar
      run: zip -r -j code-deploy code-deploy/*
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Upload to S3
      run: aws s3 cp code-deploy.zip s3://${BUCKET}/artifact/${PROJECT_NAME}-${GITHUB_SHA}.zip --region ap-northeast-2
    - name: Code Deploy
      run: aws deploy create-deployment --application-name ${PROJECT_NAME} --deployment-group-name depromeet-8th-warming-up-1-deploy --region ap-northeast-2 --s3-location bucket=${BUCKET},bundleType=zip,key=artifact/${PROJECT_NAME}-${GITHUB_SHA}.zip
    - name: Clear Deploy DIR
      run: rm -rf code-deploy
